terraform {
  required_version = ">= 1.5.0"

  # Partial backend: bucket/key/region supplied via -backend-config=backend.hcl
  # (generated by scripts/00-bootstrap-tf-backend.sh or Jenkins tf-init stage).
  backend "s3" {}

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.region
}
