apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  {{- $role := .Values.serviceAccount.roleArn | default "" }}
  {{- if and $role (not (hasPrefix "__" $role)) }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn | quote }}
  {{- end }}
