name: Build
agent: laptop
steps:
  - "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}"
  - "docker build -t ${ECR_REPO}:${BUILD_NUMBER} ./image-captioning"
  - "docker tag ${ECR_REPO}:${BUILD_NUMBER} ${ECR_REGISTRY}/${ECR_REPO}:${BUILD_NUMBER}"
  - "docker push ${ECR_REGISTRY}/${ECR_REPO}:${BUILD_NUMBER}"
